#!/bin/bash -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ -z "$CW_PATH" ]; then
  if [ -d "../clinwiki" ]; then
    echo "Using $(stat -f "%N" "../clinwiki") as \$CW_PATH"
    export CW_PATH="../clinwiki"
  else
    echo "CW_PATH not set. Call `export CW_PATH=$YOUR_CW_PATH`"
    exit 1
  fi
fi

yarn install && \
yarn build:clean && \
time NODE_ENV=production yarn build && \
rm -f $CW_PATH/public/*.chunk.js && \
rm -f $CW_PATH/public/main*.js && \
cp build/* $CW_PATH/public/.
