#!/bin/bash -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR/..
CW_PATH=..

yarn install && \
yarn build:clean && \
time NODE_ENV=production yarn build && \
rm -f $CW_PATH/public/*.chunk.js && \
rm -f $CW_PATH/public/main*.js && \
cp build/* $CW_PATH/public/.
