export const aggsOrdered = [
  'average_rating',
  // 'tags',
  'browse_condition_mesh_terms',
  'browse_interventions_mesh_terms',
  'condtions',
  'design_outcome_measures',
  'expanded_access_type_treatment',
  'facility_cities',
  'facility_countries',
  'facility_names',
  'facility_states',
  'first_received_results',
  'interventions_mesh_terms',
  'indexed_at',
  'results_first_submitted_date',
  'last_changed_date',
  'last_update_posted_date',
  'number_of_arms',
  'number_of_groups',
  'overall_status',
  'phase',
  'plan_to_share_ipd',
  'rating_dimensions',
  'reactions.kind',
  'sponsors',
  'start_date',
  'study_type',
  'study_views_count',
  'why_stopped',
  'wiki_page_edits.email',
  'wiki_page_edits.created_at',
];

export const studyFields = [
  // own fields
  'nct_id',
  'nlm_download_date_description',
  'study_first_submitted_date',
  'results_first_submitted_date',
  'disposition_first_submitted_date',
  'last_update_submitted_date',
  'study_first_submitted_qc_date',
  'study_first_posted_date',
  'study_first_posted_date_type',
  'results_first_submitted_qc_date',
  'results_first_posted_date',
  'results_first_posted_date_type',
  'disposition_first_submitted_qc_date',
  'disposition_first_posted_date',
  'disposition_first_posted_date_type',
  'last_update_submitted_qc_date',
  'last_update_posted_date',
  'last_update_posted_date_type',
  'start_month_year',
  'start_date_type',
  'start_date',
  'verification_month_year',
  'verification_date',
  'completion_month_year',
  'completion_date_type',
  'completion_date',
  'primary_completion_month_year',
  'primary_completion_date_type',
  'primary_completion_date',
  'target_duration',
  'study_type',
  'acronym',
  'baseline_population',
  'brief_title',
  'official_title',
  'overall_status',
  'last_known_status',
  'phase',
  'enrollment',
  'enrollment_type',
  'source',
  'limitations_and_caveats',
  'number_of_arms',
  'number_of_groups',
  'why_stopped',
  'has_expanded_access',
  'expanded_access_type_individual',
  'expanded_access_type_intermediate',
  'expanded_access_type_treatment',
  'has_dmc',
  'is_fda_regulated_drug',
  'is_fda_regulated_device',
  'is_unapproved_device',
  'is_ppsd',
  'is_us_export',
  'biospec_retention',
  'biospec_description',
  'ipd_time_frame',
  'ipd_access_criteria',
  'ipd_url',
  'plan_to_share_ipd',
  'plan_to_share_ipd_description',
  // derived fields
  'average_rating',
];

export const starColor = '#7ed964';

export const MAX_WINDOW_SIZE = 10000;

export const DEFAULT_SEARCH_HASH = 'ANUr6Wwa';

export const STRING_MISSING_IDENTIFIER = '-99999999999';
export const DATE_MISSING_IDENTIFIER = '1500-01-01';
