/**
 * Autogenerated input type of CreateSite
 */
export interface CreateSiteInput {
    name: string;
    subdomain: string;
    skipLanding?: boolean | null;
    hideDonation?: boolean | null;
    themes?: string | null;
    reactionsConfig?: string | null;
    userRank?: string | null;
    editorEmails?: string[] | null;
    clientMutationId?: string | null;
  }