/* tslint:disable */
/* eslint-disable */
// @generated
// This file was automatically generated and should not be edited.

// ====================================================
// GraphQL mutation operation: DeleteSiteMutation
// ====================================================

export interface DeleteSiteMutation_deleteSite_site {
  __typename: "Site";
  id: number;
}

export interface DeleteSiteMutation_deleteSite {
  __typename: "DeleteSitePayload";
  site: DeleteSiteMutation_deleteSite_site | null;
}

export interface DeleteSiteMutation {
  deleteSite: DeleteSiteMutation_deleteSite | null;
}

/**
 * Autogenerated input type of DeleteSite
 */
interface DeleteSiteInput {
  id: number;
  clientMutationId?: string | null;
}

export interface DeleteSiteMutationVariables {
  input: DeleteSiteInput;
}
