/**
 * Autogenerated input type of CreateSite
 */
export interface CreateSiteInput {
    name: string;
    subdomain: string;
    skipLanding?: boolean | null;
    hideDonation?: boolean | null;
    themes?: string | null;
    reactionsConfig?: string | null;
    userRank?: string | null;
    editorEmails?: string[] | null;
    clientMutationId?: string | null;
  }


  /**
 * Autogenerated input type of UpdateSite
 */
export interface UpdateSiteInput {
  id: number;
  name?: string | null;
  themes?: string | null;
  reactionsConfig?: string | null;
  userRank?: string | null;
  skipLanding?: boolean | null;
  hideDonation?: boolean | null;
  subdomain?: string | null;
  editorEmails?: string[] | null;
  clientMutationId?: string | null;
}

/**
 * Autogenerated input type of UpdateSiteView
 */
export interface UpdateSiteViewInput {
  name?: string | null;
  default?: boolean | null;
  url?: string | null;
  type?: string | null;
  description?: string | null;
  id: number;
  mutations: SiteViewMutationInput[];
  clientMutationId?: string | null;
}

