


/**
 * Possible set of operations of site view
 */
export enum SiteViewOperation {
    DELETE = "DELETE",
    PUSH = "PUSH",
    SET = "SET",
  }
  

/**
 * An atomic mutation of site
 */
export interface SiteViewMutationInput {
    path: string[];
    operation: SiteViewOperation;
    payload: string;
  }

/**
 * Autogenerated input type of UpdatePageView
 */
export interface UpdatePageViewInput {
    title?: string | null;
    template?: string | null;
    pageType?: string | null;
    url?: string | null;
    default?: boolean | null;
    mutations?: SiteViewMutationInput[] | null;
    id: number;
    clientMutationId?: string | null;
  }
  