aact_sync:
  cron: "0 0 * * *"
  class: "AactSync"
  queue: default
  args:
    days_ago: <%= ENV['AUTO_INDEX_LAST_DAYS'] || 1 %>

searchkick_study_queue:
  cron: "*/5 * * * * *" # every 5 seconds
  class: "ProcessQueueJob"
  queue: searchkick
  args:
    class_name: "Study"
