default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  secret_key_base: aa3312a3dc6c430194e3cab28b163c6b
  secret_token: a10cf51ecdc74c778b2d2cdff974c10f

test:
  secret_key_base: aa3312a3dc6c430194e3cab28b163c6b
  secret_token: a10cf51ecdc74c778b2d2cdff974c10f

staging:
  <<: *default

production:
  <<: *default

docker:
  <<: *default

docker_test:
  <<: *default
