require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DisplayConfigurationsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # DisplayConfiguration. As you add validations to DisplayConfiguration, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DisplayConfigurationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all display_configurations as @display_configurations" do
      display_configuration = DisplayConfiguration.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:display_configurations)).to eq([display_configuration])
    end
  end

  describe "GET #show" do
    it "assigns the requested display_configuration as @display_configuration" do
      display_configuration = DisplayConfiguration.create! valid_attributes
      get :show, {:id => display_configuration.to_param}, valid_session
      expect(assigns(:display_configuration)).to eq(display_configuration)
    end
  end

  describe "GET #new" do
    it "assigns a new display_configuration as @display_configuration" do
      get :new, {}, valid_session
      expect(assigns(:display_configuration)).to be_a_new(DisplayConfiguration)
    end
  end

  describe "GET #edit" do
    it "assigns the requested display_configuration as @display_configuration" do
      display_configuration = DisplayConfiguration.create! valid_attributes
      get :edit, {:id => display_configuration.to_param}, valid_session
      expect(assigns(:display_configuration)).to eq(display_configuration)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new DisplayConfiguration" do
        expect {
          post :create, {:display_configuration => valid_attributes}, valid_session
        }.to change(DisplayConfiguration, :count).by(1)
      end

      it "assigns a newly created display_configuration as @display_configuration" do
        post :create, {:display_configuration => valid_attributes}, valid_session
        expect(assigns(:display_configuration)).to be_a(DisplayConfiguration)
        expect(assigns(:display_configuration)).to be_persisted
      end

      it "redirects to the created display_configuration" do
        post :create, {:display_configuration => valid_attributes}, valid_session
        expect(response).to redirect_to(DisplayConfiguration.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved display_configuration as @display_configuration" do
        post :create, {:display_configuration => invalid_attributes}, valid_session
        expect(assigns(:display_configuration)).to be_a_new(DisplayConfiguration)
      end

      it "re-renders the 'new' template" do
        post :create, {:display_configuration => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested display_configuration" do
        display_configuration = DisplayConfiguration.create! valid_attributes
        put :update, {:id => display_configuration.to_param, :display_configuration => new_attributes}, valid_session
        display_configuration.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested display_configuration as @display_configuration" do
        display_configuration = DisplayConfiguration.create! valid_attributes
        put :update, {:id => display_configuration.to_param, :display_configuration => valid_attributes}, valid_session
        expect(assigns(:display_configuration)).to eq(display_configuration)
      end

      it "redirects to the display_configuration" do
        display_configuration = DisplayConfiguration.create! valid_attributes
        put :update, {:id => display_configuration.to_param, :display_configuration => valid_attributes}, valid_session
        expect(response).to redirect_to(display_configuration)
      end
    end

    context "with invalid params" do
      it "assigns the display_configuration as @display_configuration" do
        display_configuration = DisplayConfiguration.create! valid_attributes
        put :update, {:id => display_configuration.to_param, :display_configuration => invalid_attributes}, valid_session
        expect(assigns(:display_configuration)).to eq(display_configuration)
      end

      it "re-renders the 'edit' template" do
        display_configuration = DisplayConfiguration.create! valid_attributes
        put :update, {:id => display_configuration.to_param, :display_configuration => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested display_configuration" do
      display_configuration = DisplayConfiguration.create! valid_attributes
      expect {
        delete :destroy, {:id => display_configuration.to_param}, valid_session
      }.to change(DisplayConfiguration, :count).by(-1)
    end

    it "redirects to the display_configurations list" do
      display_configuration = DisplayConfiguration.create! valid_attributes
      delete :destroy, {:id => display_configuration.to_param}, valid_session
      expect(response).to redirect_to(display_configurations_url)
    end
  end

end
